routes/web.php
<?php

use App\Http\Controllers\CarouselController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'welcome']);
Route::get('/categories/{category}/product', [WelcomeController::class, 'productList'])->name('frontend.products.index');
Route::get('/products/{product}', [WelcomeController::class, 'productDetails'])->name('frontend.products.show');

require __DIR__ . '/auth.php';


Route::middleware('auth')->prefix('dashboard')->group(function () {

    Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store');

    Route::get('/home', function () {
        return view('home');
    });

    Route::get('carousels-trash', [CarouselController::class, 'trash'])->name('carousels.trash');
    Route::patch('carousels-trash/{id}', [CarouselController::class, 'restore'])->name('carousels.restore');
    Route::delete('carousels-trash/{id}', [CarouselController::class, 'delete'])->name('carousels.delete');
    Route::resource('carousels', CarouselController::class);
    Route::get('category-trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::patch('category-trash/{id}', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('category-trash/{id}', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::get('categories/pdf', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');

    Route::resource('categories', CategoryController::class);

    Route::get('colors-trash', [ColorController::class, 'trash'])->name('colors.trash');
    Route::patch('colors-trash/{id}', [ColorController::class, 'restore'])->name('colors.restore');
    Route::delete('colors-trash/{id}', [ColorController::class, 'delete'])->name('colors.delete');
    Route::get('colors/pdf', [ColorController::class, 'downloadPdf'])->name('colors.pdf');

    Route::resource('colors', ColorController::class);

    Route::get('products-trash', [ProductController::class, 'trash'])->name('products.trash');
    Route::patch('products-trash/{id}', [ProductController::class, 'restore'])->name('products.restore');
    Route::delete('products-trash/{id}', [ProductController::class, 'delete'])->name('products.delete');
    Route::get('products/pdf', [ProductController::class, 'downloadPdf'])->name('products.pdf');
    Route::resource('products', ProductController::class);

    Route::get('/profile', function () {
        return view('users.profile');
    });

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('/{user}', [UserController::class, 'show'])->name('show');
        Route::get('/{user}/change-role', [UserController::class, 'changeRole'])->name('change_role');
        Route::patch('/{user}/change-role', [UserController::class, 'updateRole'])->name('update_role');
    });
});



Route::fallback(function () {
    dd('Tomar chaoa puron korte parbona.....');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function colors()
    {
        return $this->belongsToMany(Color::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Color;
use App\Models\Product;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;
use Image;

class ProductController extends Controller
{
    public function index()
    {
        $paginatePerPage = 20;
        $serialNo = 1;
        if($pageNumber = request('page')){
            $serialNo = $paginatePerPage * ($pageNumber-1) + 1;
        }
        
        $products = Product::with('category')->latest()->paginate($paginatePerPage);
        return view('products.index', compact('products', 'serialNo'));
    }

    public function create()
    {
        $categories = Category::pluck('name', 'id')->toArray();
        $colors = Color::pluck('title', 'id')->toArray();

        return view('products.create', compact('categories', 'colors'));
    }

    public function store(ProductRequest $request)
    {
        
        $data = [
            'category_id' => $request->category_id,
            'title' => $request->title,
            'is_active' => $request->is_active ? true : false,
            'description' => $request->description,
            'image' =>  $this->uploadImage($request->file('image'))
        ];

        $product = Product::create($data);

        $product->colors()->attach($request->colors);

        return redirect()
            ->route('products.index')
            ->withMessage('Created Successfully!');
    }

    public function edit(Product $product)
    {
        $categories = Category::pluck('name', 'id')->toArray();
        $colors = Color::pluck('title', 'id')->toArray();

        $selectedColors = $product->colors()->pluck('id')->toArray(); 

        return view('products.edit', compact('product', 'categories', 'colors', 'selectedColors'));
    }

    public function update(ProductRequest $request,Product $product)
    {
        $data = [
            'category_id' => $request->category_id,
            'title' => $request->title,
            'is_active' => $request->is_active ? true : false,
            'description' => $request->description,
        ];

        if($request->hasFile('image')){
            $data['image'] = $this->uploadImage($request->file('image'));
        }

        $product->update($data);

        $product->colors()->sync($request->colors);

        return redirect()
            ->route('products.index')
            ->withMessage('Updated Successfully!');
    }

    public function show(Product $product)
    {
        return view('products.show', compact('Product'));
    }

    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()
            ->route('products.index')
            ->withMessage('Deleted Successfully!');
    }

    public function trash()
    {
        $products = Product::onlyTrashed()->get();
        return view('products.trash', compact('products'));
    }

    public function restore($id)
    {
        $product = Product::onlyTrashed()->find($id);
        $product->restore();

        return redirect()
            ->route('products.trash')
            ->withMessage('Restored Successfully!');
    } 

    public function delete($id)
    {
        $product = Product::onlyTrashed()->find($id);
        $product->colors()->detach();
        $product->forceDelete();

        return redirect()
            ->route('products.trash')
            ->withMessage('Deleted Successfully!');
    } 

    public function downloadPdf()
    {
        $products = Product::all();
        $pdf = Pdf::loadView('products.pdf', compact('products'));
        return $pdf->download('Product-list.pdf');
    }

    public function uploadImage($file){
        $fileName = date('y-m-d').'-'.time().'.'.$file ->getClientOriginalExtension();
        // $file->move(storage_path('app/public/products'), $fileName);

        Image::make($file)
                ->resize(200, 200)
                ->save(storage_path() . '/app/public/products/' . $fileName);

        return $fileName;
    }
}

resources/views/products/create.blade.php
<x-master>
    <x-slot:title>
        Product Create
    </x-slot>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Product Create</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('categories.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <x-forms.errors />

    <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
        @csrf

        <x-forms.select name="category_id" label="Category" :options="$categories" :selected="old('category_id')" required/>

        <x-forms.input type="text" name="title" label="Title" :value="old('title')" required placeholder="Enter name" />

        <x-forms.input type="file" name="image" label="Image"/>

        <x-forms.textarea name="description" :value="old('description')" label="Description" />

        <x-forms.checkbox name="colors[]" :checklist="$colors" label="Colors"/>

        <div class="mb-3">
            <label class="form-check-label">Status</label>
        </div>
        <div class="mb-3 form-check">
            <input name="is_active" type="checkbox" class="form-check-input" id="isActiveInput" value="1">
            <label class="form-check-label" for="isActiveInput">Is Active ?</label>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</x-master>

resources/views/products/edit.blade.php
<x-master>
    <x-slot:title>
        Product Edit
    </x-slot:title>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Product Edit</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{{ route('products.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <x-forms.errors />

    <form action="{{ route('products.update', $product->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('patch')

        <x-forms.select name="category_id" label="Category" :options="$categories" :selected="old('category_id', $product->category_id)" required/>

        <x-forms.input type="text" name="title" label="Title" :value="old('title', $product->title)" required placeholder="Enter name" />

        <img src="{{ asset('storage/products/'.$product->image) }}" height="250" />

        <x-forms.input type="file" name="image" label="Image"/>

        {{-- select, checkbox, radio, texarea --}}

        <x-forms.textarea name="description" :value="old('description', $product->description)" label="Description" />

        <x-forms.checkbox name="colors[]" id="color" :checklist="$colors" :checkedItems="$selectedColors" label="Colors"/>

        <x-forms.checkbox name="is_active" :checklist="[1 =>'Is Active']" :checkedItems="[$product->is_active]" label="Colors"/>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</x-master>

resources/views/products/index.blade.php
<x-master>
    <x-slot:title>
        Product List
        </x-slot>

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Products</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('products.pdf') }}">
                        <button type="button" class="btn btn-sm btn-outline-primary">PDF</button>
                    </a>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export Excel</button>
                    <a href="{{ route('products.trash') }}">
                        <button type="button" class="btn btn-sm btn-outline-danger">Trash</button>
                    </a>
                </div>
                <a href="{{ route('products.create') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="plus"></span>
                        Add New
                    </button>
                </a>
            </div>
        </div>

        <x-forms.message />

        <table class="table">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th width="180">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($products as $product)
                <tr>
                    <td>{{ $serialNo ++ }}</td>
                    <td>{{ $product->title }}</td>
                    <td>{{ $product->category?->name }}</td>
                    <td class="d-flex">
                        <a class="btn btn-sm btn-outline-info" href="{{ route('products.show', $product->id) }}">Show</a>

                        <a class="btn btn-sm btn-outline-info" href="{{ route('products.edit', $product->id) }}">Edit</a>

                        <form action="{{ route('products.destroy', $product->id) }}" method="post">
                            @csrf
                            @method('delete')
                            <button class="btn btn-sm btn-outline-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        {{ $products->links() }}

</x-master>

resources/views/products/pdf.blade.php
<table border="1">
    <thead>
        <tr>
            <th>SL#</th>
            <th>Title</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $category->name }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/products/show.blade.php
<x-master>
    <x-slot:title>
        Category Details
    </x-slot:title>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Category Details</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Export PDF</button>
            </div>
            <a href="{{ route('categories.index') }}">
                <button type="button" class="btn btn-sm btn-outline-primary">
                    <span data-feather="list"></span>
                    List
                </button>
            </a>
        </div>
    </div>

    <h1>Title: {{ $category->name }}</h1>
    <p>Is Active?: {{ $category->is_active ? 'Yes' : 'No' }} </p>
    <img src="{{ asset('storage/categories/'.$category->image) }}" height="250" />
</x-master>

resources/views/products/trash.blade.php
<x-master>
    <x-slot:title>
        Product List
        </x-slot>

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Product Trash List</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export PDF</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export Excel</button>
                    <a href="{{ route('products.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-info">List</button>
                    </a>
                </div>
               
            </div>
        </div>

        <x-forms.message />

        <table class="table">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Title</th>
                    <th width="180">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($products as $product)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $product->title }}</td>
                    <td class="d-flex">
                        <form action="{{ route('products.restore', $product->id) }}" method="post">
                            @csrf
                            @method('patch')
                            <button class="btn btn-sm btn-outline-warning" onclick="return confirm('Are you sure want to restore?')">Restore</button>
                        </form>
                        <form action="{{ route('products.delete', $product->id) }}" method="post">
                            @csrf
                            @method('delete')
                            <button class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure want to delete?')">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

</x-master>